
services:
  db:
    image: postgres:16
    container_name: pg
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d appdb"]
      interval: 5s
      timeout: 3s
      retries: 15

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: api
    depends_on:
      db:
        condition: service_healthy
    environment:
      NODE_ENV: production
      PORT: "3000"
      # Prisma usa o host "db" (nome do serviço) dentro da rede do compose
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/appdb?schema=public"
      # outras variáveis necessárias ao seu app:
      JWT_SECRET: "changeme-local"
    ports:
      - "3001:3000"   # API disponível em http://localhost:3001
    restart: unless-stopped
    # o entrypoint do Dockerfile já roda migrate/seed antes de subir

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: web
    depends_on:
      - backend
    environment:
      VITE_API_URL: "http://localhost:3001"
    ports:
      - "3000:5173"   # Front disponível em http://localhost:3000
    restart: unless-stopped

volumes:
  pgdata:
